<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>ab4bc0a3-ba49-4ff0-92f9-106516f45f31</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourtBooking.Application\CourtBooking.Application.csproj" />
    <ProjectReference Include="..\CourtBooking.Domain\CourtBooking.Domain.csproj" />
    <ProjectReference Include="..\CourtBooking.Infrastructure\CourtBooking.Infrastructure.csproj" />
    <ProjectReference Include="..\CourtBooking.SharedKernel\CourtBooking.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
