// <auto-generated />
using System;
using CourtBooking.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourtBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AccountNumer");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<Guid>("CourtOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GgMapUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GGMapUrl");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("Policy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("QrImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtOwnerId")
                        .HasDatabaseName("IX_Branches_CourtOwnerId");

                    b.HasIndex("QrImageId");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.BranchImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_BranchImages_BranchId");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("IX_BranchImages_ImageId");

                    b.ToTable("BranchImages", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.BranchSportType", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SportTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BranchId", "SportTypeId");

                    b.HasIndex("SportTypeId");

                    b.ToTable("BranchSportTypes", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourtTyped");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtTypeId")
                        .HasDatabaseName("IX_Courts_CourtTyped");

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.CourtType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesConfig")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_CourtTypes_BranchId");

                    b.ToTable("CourtTypes", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.FixedTimeBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("int")
                        .HasComment("Lưu theo kiểu bitwise");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtTypeId")
                        .HasDatabaseName("IX_FixedTimeBlock_CourtTypeId");

                    b.ToTable("FixedTimeBlock", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.FixedTimeBlockCourt", b =>
                {
                    b.Property<Guid>("FixedTimeBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FixedTimeBlockId", "CourtId");

                    b.HasIndex("CourtId")
                        .HasDatabaseName("IX_FixedTimeBlockCourts_CourtId");

                    b.ToTable("FixedTimeBlockCourts", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.PriceTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtTypeId")
                        .HasDatabaseName("IX_PriceTables_CourtTypeId");

                    b.ToTable("PriceTables", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.PriceTableRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DayOfWeekFrom")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DayOfWeekTo")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("FixedCustomerPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PriceTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("WalkInCustomerPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PriceTableId")
                        .HasDatabaseName("IX_PriceTableRules_PriceTableId");

                    b.ToTable("PriceTableRules", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.SportType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("SportType", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Events.EventTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint")
                        .HasComment("1=Tiền mặt, 2=Chuyển khoản QR");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProofImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ImageId ảnh chụp màn hình CK - NULL nếu trả tiền mặt tại chỗ");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("RefundNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Lý do/ghi chú hoàn tiền nếu Status=Refunded");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EventTickets_EventId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_EventTickets_PlayerId");

                    b.HasIndex("ProofImageId");

                    b.ToTable("EventTickets", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Events.SportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableSlot")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillLevelFrom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SkillLevelTo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<Guid>("SportTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasComment("0:Open, 1:Full, 2:Closed, 3:Cancelled");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("SportTypeId")
                        .HasDatabaseName("IX_Events_SportTypeId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AttachedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("public_id/object key - dùng để gọi API xoá file thật trên storage");

                    b.Property<byte>("StorageProvider")
                        .HasColumnType("tinyint")
                        .HasComment("1=Cloudinary, 2=S3, 3=AzureBlob");

                    b.HasKey("Id");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Matches.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HoldExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasComment("0: PendingApproval, 1: PendingPayment, 2: Confirmed, 3: Rejected, 4: Cancelled, 5: Expired");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MatchParticipants_PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MatchParticipants_MatchId_PlayerId");

                    b.ToTable("MatchParticipants", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Matches.SocialMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ApprovalMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasComment("0: Tự động duyệt, 1: Chủ kèo duyệt tay");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("FeePerPlayer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MissingPlayers")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SportTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasComment("0: Open, 1: Full, 2: Closed, 3: Cancelled");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_SocialMatches_BranchId");

                    b.HasIndex("HostId")
                        .HasDatabaseName("IX_SocialMatches_HostId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("SportTypeId")
                        .HasDatabaseName("IX_SocialMatches_SportTypeId");

                    b.ToTable("SocialMatches", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.FixedOrderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ExceptionDates")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_FixedOrderConfigs_OrderId");

                    b.ToTable("FixedOrderConfigs", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.FixedOrderConfigCourt", b =>
                {
                    b.Property<Guid>("FixedOrderConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FixedOrderConfigId", "CourtId");

                    b.HasIndex("CourtId")
                        .HasDatabaseName("IX_FixedOrderConfigCourts_CourtId");

                    b.ToTable("FixedOrderConfigCourts", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("HoldExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<byte>("OrderType")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<decimal>("TotalCourtAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalServiceAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Orders_BranchId");

                    b.HasIndex("HoldExpiresAt")
                        .HasDatabaseName("IX_Orders_HoldExpiresAt")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_Orders_PlayerId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrdersDetails_OrderId");

                    b.HasIndex("CourtId", "Date", "StartTime")
                        .HasDatabaseName("IX_OrdersDetails_CourtId_Date_StartTime");

                    b.ToTable("OrdersDetails", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.OrderService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderServices_OrderId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_OrderServices_ServiceId");

                    b.ToTable("OrderServices", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Payments.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Method")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Nullable: null nếu đây là giao dịch của người chơi tham gia kèo");

                    b.Property<Guid?>("ProofImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasComment("1: Thanh toán, 2: Hoàn tiền");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_PaymentTransactions_OrderId");

                    b.HasIndex("ProofImageId");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Reviews_BranchId");

                    b.HasIndex("ImageId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.RetailOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_RetailOrder_BranchId");

                    b.ToTable("RetailOrder", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.RetailOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RetailOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RetailOrderId")
                        .HasDatabaseName("IX_RetailOrderItems_RetailOrderId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_RetailOrderItems_ServiceId");

                    b.ToTable("RetailOrderItems", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Services_CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.ServiceBranch", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceId", "BranchId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_ServiceBranches_BranchId");

                    b.ToTable("ServiceBranches", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtOwnerId", "Name")
                        .IsUnique();

                    b.ToTable("ServiceCategories", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Subscriptions.CourtOwnerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PricePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ServicePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CourtOwnerId")
                        .HasDatabaseName("IX_CourtOwnerSubscriptions_CourtOwnerId");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("IX_CourtOwnerSubscriptions_ServicePackageId");

                    b.ToTable("CourtOwnerSubscriptions", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Subscriptions.ServicePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("DurationMonths")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ServicePackages", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.CourtOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePwd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("QrImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QrImageId");

                    b.ToTable("CourtOwners", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AvatarImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AvatarImageId");

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.Branch", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.CourtOwner", "CourtOwner")
                        .WithMany("Branches")
                        .HasForeignKey("CourtOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "QrImage")
                        .WithMany()
                        .HasForeignKey("QrImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourtOwner");

                    b.Navigation("QrImage");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.BranchImage", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("Images")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.BranchSportType", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("BranchSportTypes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Courts.SportType", "SportType")
                        .WithMany("BranchSportTypes")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.Court", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.CourtType", "CourtType")
                        .WithMany("Courts")
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtType");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.CourtType", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("CourtTypes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.FixedTimeBlock", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.CourtType", "CourtType")
                        .WithMany("FixedTimeBlocks")
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourtType");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.FixedTimeBlockCourt", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Court", "Court")
                        .WithMany("FixedTimeBlockCourts")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Courts.FixedTimeBlock", "FixedTimeBlock")
                        .WithMany("Courts")
                        .HasForeignKey("FixedTimeBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("FixedTimeBlock");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.PriceTable", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.CourtType", "CourtType")
                        .WithMany("PriceTables")
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtType");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.PriceTableRule", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.PriceTable", "PriceTable")
                        .WithMany("Rules")
                        .HasForeignKey("PriceTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceTable");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.SportType", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Events.EventTicket", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Events.SportEvent", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "Player")
                        .WithMany("EventTickets")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "ProofImage")
                        .WithMany()
                        .HasForeignKey("ProofImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Player");

                    b.Navigation("ProofImage");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Events.SportEvent", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithOne("SportEvent")
                        .HasForeignKey("CourtBooking.Domain.Entities.Events.SportEvent", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Courts.SportType", "SportType")
                        .WithMany("Events")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Matches.MatchParticipant", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Matches.SocialMatch", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "Player")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Matches.SocialMatch", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("SocialMatches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithOne("SocialMatch")
                        .HasForeignKey("CourtBooking.Domain.Entities.Matches.SocialMatch", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Courts.SportType", "SportType")
                        .WithMany("SocialMatches")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Host");

                    b.Navigation("Order");

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.FixedOrderConfig", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithMany("FixedConfigs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.FixedOrderConfigCourt", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Court", "Court")
                        .WithMany("FixedOrderConfigCourts")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Orders.FixedOrderConfig", "FixedOrderConfig")
                        .WithMany("Courts")
                        .HasForeignKey("FixedOrderConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("FixedOrderConfig");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "Player")
                        .WithMany("Orders")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.OrderDetail", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Court", "Court")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.OrderService", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithMany("Services")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Services.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Payments.PaymentTransaction", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "ProofImage")
                        .WithMany()
                        .HasForeignKey("ProofImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("ProofImage");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("Reviews")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CourtBooking.Domain.Entities.Orders.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "Player")
                        .WithMany("Reviews")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Image");

                    b.Navigation("Order");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.RetailOrder", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("RetailOrders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.RetailOrderItem", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Services.RetailOrder", "RetailOrder")
                        .WithMany("Items")
                        .HasForeignKey("RetailOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Services.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RetailOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.Service", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Services.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.ServiceBranch", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Courts.Branch", "Branch")
                        .WithMany("ServiceBranches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Services.Service", "Service")
                        .WithMany("Branches")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.ServiceCategory", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.CourtOwner", "CourtOwner")
                        .WithMany("ServiceCategories")
                        .HasForeignKey("CourtOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourtOwner");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Subscriptions.CourtOwnerSubscription", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.CourtOwner", "CourtOwner")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CourtOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Subscriptions.ServicePackage", "ServicePackage")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourtOwner");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.CourtOwner", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "User")
                        .WithOne("CourtOwner")
                        .HasForeignKey("CourtBooking.Domain.Entities.Users.CourtOwner", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "QrImage")
                        .WithMany()
                        .HasForeignKey("QrImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QrImage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.PlayerProfile", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Images.Image", "AvatarImage")
                        .WithMany()
                        .HasForeignKey("AvatarImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("CourtBooking.Domain.Entities.Users.PlayerProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvatarImage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CourtBooking.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.Branch", b =>
                {
                    b.Navigation("BranchSportTypes");

                    b.Navigation("CourtTypes");

                    b.Navigation("Images");

                    b.Navigation("Orders");

                    b.Navigation("RetailOrders");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceBranches");

                    b.Navigation("SocialMatches");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.Court", b =>
                {
                    b.Navigation("FixedOrderConfigCourts");

                    b.Navigation("FixedTimeBlockCourts");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.CourtType", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("FixedTimeBlocks");

                    b.Navigation("PriceTables");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.FixedTimeBlock", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.PriceTable", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Courts.SportType", b =>
                {
                    b.Navigation("BranchSportTypes");

                    b.Navigation("Events");

                    b.Navigation("SocialMatches");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Events.SportEvent", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Matches.SocialMatch", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.FixedOrderConfig", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("FixedConfigs");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("Reviews");

                    b.Navigation("Services");

                    b.Navigation("SocialMatch");

                    b.Navigation("SportEvent");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.RetailOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.Service", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Services.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Subscriptions.ServicePackage", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("CourtOwner");

                    b.Navigation("EventTickets");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Orders");

                    b.Navigation("PlayerProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CourtBooking.Domain.Entities.Users.CourtOwner", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("ServiceCategories");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
