<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="Repositories\" />
    <Folder Include="Enums\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
  </ItemGroup>
<ItemGroup>
	 <InternalsVisibleTo Include="CourtBooking.Infrastructure" />
  <InternalsVisibleTo Include="CourtBooking.Application" />
</ItemGroup>
</Project>
